Bugfixes for DeviceManager and PropertiesObject
QubesOS/qubes-dbus pull request #5
Opened 2017-08-02 14:17 UTC by kalkin

2017-08-03 08:25 UTC, marmarek approved these changes

2017-08-03 14:17 UTC, marmarek requested changes

2017-08-03 14:17 UTC, marmarek commented on qubesdbus/service.py
> +        self.PropertiesChanged("org.freedesktop.DBus.Properties",
Hmm, shouldn't this be `self.iface`?

2017-08-07 14:23 UTC, kalkin commented
Fixed `self.iface`

2017-08-07 20:24 UTC, marmarek approved these changes

2017-08-07 20:24 UTC, merged